#Registro de configuración y últimos logins realizados por usuarios
#Sat May 02 18:16:18 CEST 2026
acceso.invitado=false
asistente2@fernanevents.com=02/05/2026 - 18\:16
flenmar918@g.educaand.es=02/05/2026 - 11\:50
organizador1@fernanevents.com=02/05/2026 - 16\:48
ruta.eventos=datosJSON/eventos.json
ruta.logs=datosJSON/registro_actividad.log
ruta.usuarios=datosJSON/usuarios.json
