#Registro de configuración y últimos logins realizados por usuarios
#Tue Jun 02 17:08:06 CEST 2026
acceso.invitado=true
admin@fernanevents.com=03/05/2026 - 16\:58
asistente1@fernanevents.com=02/06/2026 - 17\:08
asistente2@fernanevents.com=02/05/2026 - 18\:16
db.password=
db.url=jdbc\:mysql\://localhost\:3307/FernanEvents
db.user=root
flenmar918@g.educaand.es=02/05/2026 - 11\:50
organizador1@fernanevents.com=03/05/2026 - 12\:08
ruta.eventos=datosJSON/eventos.json
ruta.logs=datosJSON/registro_actividad.log
ruta.usuarios=datosJSON/usuarios.json
