#Registro de configuración y últimos logins realizados por usuarios
#Wed Jun 03 13:41:34 CEST 2026
acceso.invitado=true
admin@fernanevents.com=03/05/2026 - 16\:58
asistente1@fernanevents.com=03/06/2026 - 13\:29
asistente2@fernanevents.com=02/05/2026 - 18\:16
db.password=
db.url=jdbc\:mysql\://localhost\:3307/FernanEvents
db.user=root
flenmar918@g.educaand.es=03/06/2026 - 13\:36
josealbertuz@gmail.com=03/06/2026 - 13\:41
organizador1@fernanevents.com=03/06/2026 - 13\:26
ruta.logs=datosJSON/registro_actividad.log

