#Registro de configuración y últimos logins realizados por usuarios
#Sat Jun 06 10:44:30 CEST 2026
acceso.invitado=true
admin@fernanevents.com=06/06/2026 - 10\:44
asistente1@fernanevents.com=05/06/2026 - 17\:42
asistente2@fernanevents.com=02/05/2026 - 18\:16
db.password=PassELBLOVpsChem_121
db.url=jdbc\:mysql\://37.187.67.246\:3306/FernanEvents
db.user=profe
flenmar918@g.educaand.es=03/06/2026 - 13\:36
jmorcam520@g.educaand.es=05/06/2026 - 17\:59
josealbertuz@gmail.com=03/06/2026 - 13\:41
organizador1@fernanevents.com=03/06/2026 - 13\:26
ruta.logs=archivosConfig/registro_actividad.log
